source "$OMADORA_INSTALL/config/config.sh"
source "$OMADORA_INSTALL/config/theme.sh"
source "$OMADORA_INSTALL/config/branding.sh"
source "$OMADORA_INSTALL/config/gpg.sh"
source "$OMADORA_INSTALL/config/ssh-flakiness.sh"
source "$OMADORA_INSTALL/config/detect-keyboard-layout.sh"
source "$OMADORA_INSTALL/config/xcompose.sh"
source "$OMADORA_INSTALL/config/mise-work.sh"
source "$OMADORA_INSTALL/config/mimetypes.sh"
source "$OMADORA_INSTALL/config/user-dirs.sh"
source "$OMADORA_INSTALL/config/nautilus-python.sh"
source "$OMADORA_INSTALL/config/omadora-toggles.sh"

source "$OMADORA_INSTALL/config/hardware/network.sh"
source "$OMADORA_INSTALL/config/hardware/power.sh"
