# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = systemctl --user import-environment SSH_AUTH_SOCK
exec-once = sleep 10 && flatpak run com.synology.SynologyDrive
exec-once = sleep 10 && keepassxc --minimized
