# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

$projectsdir = $HOME/Projects/
$pyenv_path = $HOME/.local/lib/python

env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket
env = PROJECTSDIR,$projectsdir
env = PYENV_PATH,$pyenv_path

env = SSL_CERT_FILE,/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
env = REQUESTS_CA_BUNDLE,/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

# Use Omadora defaults (but don't edit these directly!)
source = ~/.local/share/omadora/default/hypr/autostart.conf
source = ~/.local/share/omadora/default/hypr/bindings/media.conf
source = ~/.local/share/omadora/default/hypr/bindings/tiling.conf
source = ~/.local/share/omadora/default/hypr/bindings/utilities.conf
source = ~/.local/share/omadora/default/hypr/looknfeel.conf
source = ~/.local/share/omadora/default/hypr/input.conf
source = ~/.local/share/omadora/default/hypr/windows.conf
source = ~/.config/omadora/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/windows.conf

# Toggle config flags dynamically
source = ~/.local/state/omadora/toggles/hypr/*.conf
