general {
    lock_cmd = omactl session lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = omactl display brightness on
    inhibit_sleep = 3
}

# Start screensaver after 2.5 minutes
listener {
    timeout = 300
    on-timeout = pidof hyprlock || omactl session screensaver
}

# Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Screen off after 7.5 minutes
listener {
    timeout = 150
    on-timeout = omactl display brightness off
    on-resume = omactl display brightness on
}
