# Add custom window config in this file.

# Tag Chromium Browser
windowrule = tag +chromium-based-browser, match:class chromium-browser
windowrule = float on, match:class ^(seahorse-tool)$
windowrule = float on, match:class ^(org\.qbittorrent\.qBittorrent)$
windowrule = float on, match:title ^(RollerCoaster Tycoon)$
windowrule = float on, match:class ^(org.keepassxc.KeePassXC)$
windowrule = float on, match:class ^(org\.gnome\.Evolution)$, match:title ^(Compose Message)$
windowrule = size 900 700, match:class ^(org\.gnome\.Evolution)$, match:title ^(Compose Message)$
