#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Overwrite all the user Hyprland Lua configs in ~/.config/hypr with the Omadora defaults.

omadora_run omadora-refresh-config hypr/.luarc.json
omadora_run omadora-refresh-config hypr/autostart.lua
omadora_run omadora-refresh-config hypr/bindings.lua
omadora_run omadora-refresh-config hypr/input.lua
omadora_run omadora-refresh-config hypr/looknfeel.lua
omadora_run omadora-refresh-config hypr/hyprland.lua
omadora_run omadora-refresh-config hypr/monitors.lua
bash "$OMADORA_PATH/install/config/omadora-toggles.sh"
bash "$OMADORA_PATH/install/config/detect-keyboard-layout.sh"
