#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Toggle single-window square aspect ratio.

case $(omadora_run omadora-hyprland-toggle single-window-aspect-ratio) in
on) notify-send -u low "    Enable single-window square aspect ratio" ;;
off) notify-send -u low "    Disable single-window square aspect ratio" ;;
esac
